baseURL = 'https://ben.bolte.cc/'
languageCode = 'en-us'
title = "Ben's Blog"

[taxonomies]
  tag = 'tags'

[params]
  description = "Personal blog of Ben Bolte"

[markup.highlight]
  style = 'github'

[menu]
  [[menu.main]]
    name = "Github"
    url = "https://github.com/codekansas"
    weight = 3
  [[menu.main]]
    name = "Twitter"
    url = "https://x.com/benjamin_bolte"
    weight = 4
  [[menu.main]]
    name = "Wiki"
    url = "https://wiki.bolte.cc"
    weight = 5
