baseURL = 'https://ben.bolte.cc/'
languageCode = 'en-us'
title = "Ben's Blog"

[taxonomies]
  tag = 'tags'

[params]
  description = "Musings about math, neuroscience and robotics"
  math = true

[markup]
  [markup.highlight]
    style = 'github'
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[menu]
  [[menu.main]]
    name = "Github"
    url = "https://github.com/codekansas"
    weight = 3
  [[menu.main]]
    name = "Twitter"
    url = "https://x.com/benjamin_bolte"
    weight = 4
